/**
 * Datos maestros institucionales.
 *
 * NOTA: estos arreglos son un placeholder estático para alimentar los
 * combos de autocompletado de la página de presupuesto. En una fase
 * posterior deberían reemplazarse por una fuente real (tabla en Supabase,
 * vista materializada, o integración con el ERP/sistema contable de la
 * institución) consultada vía Server Component o Route Handler.
 */

export const PROYECTOS_INSTITUCIONALES = [
  'GESTION Y APOYO',
  'DOCENCIA PREGRADO',
  'DOCENCIA POSGRADO',
  'DOCENCIA FORMACION EXTENSIVA',
  'INVESTIGACION',
  'PROYECCION SOCIAL',
  'BIENESTAR INSTITUCIONAL',
  'RECTORIA',
];

export const CENTROS_COSTO_INSTITUCIONALES = [
  'Selección y Desarrollo',
  'Seguridad Y Salud En El Trabajo',
  'División De Comunidad Universitaria-TH',
  'Dirección General Administrativa',
  'Almacén',
  'Compras',
  'Tesorería',
  'Facturación y Cartera',
  'División Financiera',
  'Infraestructura Tecnológica',
  'Desarrollo de Software',
  'Seguridad Informática',
  'Asamblea Fundadores',
  'Sede Administrativa',
  'Área de medios educativos',
  'Div de Tecnología Y Medios Educativos',
  'Logística',
  'Servicios Generales',
  'Mantenimiento',
  'Vehículos',
  'Dirección De Proyectos Especiales',
  'Dirección De Posicionamiento',
  'Comunicaciones',
  'Mercadeo y Publicidad',
  'Admisiones',
  'Emisora Radio Autónoma',
  'Dirección De Planeacion y Evaluacion',
  'Calidad y acreditación',
  'Planeacion y evaluacion',
  'Vic de Relacionamiento con el Entorno',
  'Egresados',
  'Rectoría',
  'Secretaría General',
  'Área De Registro y Control',
  'Archivo y correspondencia',
  'Vicerrectoría Académica',
  'Publicación Cientifica-Investigacion',
  'CD Profesoral e Innovación Educativa',
  'Proyectos De Investigación CTEL',
  'Vicerrectoría De Investigación',
  'Grupos de Investigación',
  'Sello Editorial',
  'Proyectos De Investigación',
  'Semilleros de Investigación',
  'Jovenes Investigación',
  'Bienestar Universitario',
  'Salud Integral',
  'Recreación y Deporte',
  'Desarrollo Humano',
  'Cultura',
  'Permanencia y graduación Estudiantil',
  'Indetec',
  'Rep. Legal',
  'Emprendelab',
  'Escuela de Ciencias Administrativas',
  'Escuela de Derecho',
  'Escuela de Educación',
  'Escuela de ingeniería y sostenibilidad',
  'Escuela de Negocios',
  'Consultorio Jurídico',
  'Centro acondicionamiento físico',
  'Sede Posgrados',
  'CEO-Laboratorio Emprendimiento',
  'Sede Bienestar',
  'Proyectos proyección social',
  'Sede Aljibe',
  'Sede Laboratorios',
  'Sede Química',
  'Sede Principal',
  'Obra Sala Juntas Principal',
  'Sede Electrónica',
  'Liceo tecnico superior',
];

export const UNIDADES_NEGOCIO_INSTITUCIONALES: readonly string[] = [
  'Sede Principal',
  'Sede Norte',
  'Sede Sur',
  'Operación Virtual',
  'Servicios Compartidos',
];

export const PRODUCTOS_INSTITUCIONALES: readonly string[] = [
  'Equipos de cómputo',
  'Software y licenciamiento',
  'Mobiliario y adecuaciones',
  'Papelería y suministros',
  'Servicios profesionales',
  'Mantenimiento y soporte técnico',
];
